# Generated by Django 4.2 on 2023-04-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FarmingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Greenhouse', 'Greenhouse')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InputUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Complete', 'Complete'), ('Partial', 'Partial')], max_length=255)),
                ('done', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValueChainChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Poultry', 'Poultry'), ('Vegetable', 'Vegetable'), ('Herbs', 'Herbs'), ('Dairy', 'Dairy')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Borehole', 'Borehole'), ('River', 'River'), ('Dam', 'Dam'), ('Rain', 'Rain'), ('Swamp', 'Swamp')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('id_number', models.FloatField(max_length=8)),
                ('mobile_number', models.CharField(max_length=13)),
                ('plot_size', models.FloatField()),
                ('farming_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.farmingtype')),
                ('inputs_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.inputused')),
                ('producer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.producergroup')),
                ('soil_test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.soiltestresult')),
                ('value_chain_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.valuechainchoice')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.watersource')),
            ],
        ),
    ]
