# Generated by Django 4.2 on 2023-05-01 17:28

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=55)),
                ('length', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('is_leased', models.BooleanField(default=False)),
                ('crops', models.ManyToManyField(blank=True, related_name='crops', to='farmflow.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FarmingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Greenhouse', 'Greenhouse')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FarmInputUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Complete', 'Complete'), ('Partial', 'Partial')], max_length=255)),
                ('done', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValueChainChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Poultry', 'Poultry'), ('Vegetable', 'Vegetable'), ('Herbs', 'Herbs'), ('Dairy', 'Dairy')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Borehole', 'Borehole'), ('River', 'River'), ('Dam', 'Dam'), ('Rain', 'Rain'), ('Swamp', 'Swamp'), ('Other', 'other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/fevercode/image/upload/v1654534329/default_n0r7rf.png', max_length=255, verbose_name='image')),
                ('bio', models.TextField(default='This is my bio', max_length=500)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('id_number', models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(8)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('plot_size', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.cluster')),
                ('members', models.ManyToManyField(related_name='producer_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fertilizer', 'Fertilizer'), ('Pesticides', 'Pesticides')], max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.CharField(choices=[('kg', 'kg'), ('litres', 'litres')], max_length=255)),
                ('farms', models.ManyToManyField(through='farmflow.FarmInputUsed', to='farmflow.farm')),
                ('value_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.valuechainchoice')),
            ],
        ),
        migrations.AddField(
            model_name='farminputused',
            name='input_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.inputused'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farming_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.farmingtype'),
        ),
        migrations.AddField(
            model_name='farm',
            name='input_used',
            field=models.ManyToManyField(through='farmflow.FarmInputUsed', to='farmflow.inputused'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.soiltestresult'),
        ),
        migrations.AddField(
            model_name='farm',
            name='water_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.watersource'),
        ),
        migrations.CreateModel(
            name='CropProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_date', models.DateField(auto_now_add=True)),
                ('harvested_date', models.DateField(auto_now=True)),
                ('ploughing', models.DateField()),
                ('weeding', models.DateField()),
                ('harvesting', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.crop')),
                ('inputs', models.ManyToManyField(blank=True, to='farmflow.inputused')),
            ],
        ),
    ]
