# Generated by Django 4.2 on 2023-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('id_number', models.FloatField(max_length=8)),
                ('mobile_number', models.CharField(max_length=13)),
                ('plot_size', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
