# Generated by Django 4.2 on 2023-05-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropproductionstage',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmflow.farm'),
            preserve_default=False,
        ),
    ]
