# Generated by Django 4.2 on 2023-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
