# Generated by Django 4.2 on 2023-05-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='value_chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmflow.valuechainchoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(default='8d4501d4-b498-4ecd-94bf-d4c7467d6175', editable=False, max_length=36, unique=True),
        ),
    ]
