# Generated by Django 4.2 on 2023-05-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0002_alter_profile_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputused',
            name='quantity',
        ),
    ]
