# Generated by Django 4.2 on 2023-05-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0002_alter_produce_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmflow.profile'),
        ),
    ]
