# Generated by Django 4.2 on 2023-05-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0002_cropproductionstage_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='producer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmflow.producergroup'),
        ),
    ]
