# Generated by Django 4.2 on 2023-05-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmflow', '0003_alter_produce_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropproductionstage',
            name='harvested_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cropproductionstage',
            name='planted_date',
            field=models.DateField(),
        ),
    ]
